### ISSUE TITLE
一个小建议

### ISSUE THREAD

**Issue by starlightme** [Yixiaohan/show-me-the-code#12]
加一个图像识别（类似于验证码破解）的题会不会更好呢，谢谢

**Comment by Yixiaohan** [comment]
@starlightme  想法挺好哈。

不过，我本人暂时没有做过“验证码破解”，所以暂时不会加入的 :-)  

后期有可能会加入的。

**Comment by yeayee** [comment]
看看机器学习实战第一章即可

**Comment by starlightme** [comment]
@yeayee 好的，谢谢
