### ISSUE TITLE
where is the answer

### ISSUE THREAD

**Issue by mythxox** [Yixiaohan/show-me-the-code#14]
没有答案吗

**Comment by Yixiaohan** [comment]
@mythxox  你还是学生吗？怎么一直想着有“答案”呢？你自己写得代码就是答案。

**Comment by sbwtw** [comment]
@Yixiaohan 赞 ˊ_>ˋ

**Comment by csrgxtu** [comment]
第一个题目是要在ＱＱ里面做吗，还是一个简单的图像处理？

**Comment by Yixiaohan** [comment]
@csrgxtu  你说得是第 0000 题吧？随便找个头像图即可，知识点是图像处理第三库的使用 :-)

**Comment by csrgxtu** [comment]
@Yixiaohan , 哦，好的，懂了。

**Comment by your-simle** [comment]
just test

**Comment by Yixiaohan** [comment]
@your-simle   请站在仓库管理者，和参与此 issues 讨论者的角度想一下，「如果大家都发  just test」的话，会怎样？

**Comment by GKilyar** [comment]
刚开始学python写到第四题就卡住了。好伤心啊不会的太多了
