### ISSUE TITLE
0018 spell error

### ISSUE THREAD

**Issue by medisean** [Yixiaohan/show-me-the-code#36]
citys is wrong, cities is right.

**Comment by Yixiaohan** [comment]
谢谢，已经修正 :-)

**Comment by medisean** [comment]
0018 好像显示还是有点问题

<img width="760" alt="2017-12-04 4 44 07" src="https://user-images.githubusercontent.com/6093631/33543671-dff8eaf8-d912-11e7-98c0-b6b911bb5bc8.png">

**Comment by medisean** [comment]
@Yixiaohan

**Comment by Yixiaohan** [comment]
@medisean  谢谢，已经修正 :-)
